name: First Workflow

on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print a welcome message
      run: echo "Welcome to our first Github Actions workfolw!"
      
    - name: Checkout Repository
      uses: actions/checkout@v6.0.2

    - name: List repo files
      run: ls-la
